### ISSUE TITLE
Doubt: About the complement

### ISSUE THREAD

**Issue by DomingoMG** [caendesilva/WindowsToggleAudioDevice#1]
I liked the script, but I would like to be able to listen to the microphone device as if it were a toggle and be able to assign the output device.

In the Windows microphone settings those options appear, Is it possible? 

![Captura de pantalla 2024-07-04 193001](https://github.com/caendesilva/WindowsToggleAudioDevice/assets/36201422/a4b3d2c7-9709-4955-873f-89dccc2e7ae5)

**Comment by emmadesilva** [comment]
To confirm, you are wondering if it's possible to toggle the "Escuchar este dispositivo" (Listen to device) setting?

This script wraps this Cmdlet https://github.com/frgnca/AudioDeviceCmdlets, and I don't see an option for that there. But I did find an AutoHotKey script, does that help? https://www.reddit.com/r/AutoHotkey/comments/fritax/toggling_listen_to_this_device_setting_for_line_in/

**Comment by DomingoMG** [comment]
Thank you, that may be my solution
